routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {
    Route::get('/auth/login', 'SiteController@login');

Route::group(['middleware'=>['restrict.access']], function(){

  Route::group(array('prefix'=>'sms' ), function(){
    Route::get('/', ['as'=>'admin.sms.index', 'uses'=>'SmsController@index']);
    Route::get('send', ['as'=>'admin.sms.get', 'uses'=>'SmsController@getSend']);
    Route::post('send', ['as'=>'admin.sms.post', 'uses'=>'SmsController@postSend']);
  });


Route::group(array('prefix'=>'content'), function(){
  Route::get('/', ['as'=>'content.dashboard', 'uses'=>'SiteController@contentDashboard']);
  Route::resource('businesses', 'BusinessesController', array('names' => mzk_route_helper('businesses', 'admin')));
  Route::resource('groups', 'GroupsController', array('names' => mzk_route_helper('groups', 'admin')));
  Route::resource('categories', 'CategoriesController', array('names' => mzk_route_helper('categories', 'admin')));
  Route::resource('zones', 'ZonesController', array('names' => mzk_route_helper('zones', 'admin')));
  Route::resource('highlights', 'HighlightsController', array('names' => mzk_route_helper('highlights', 'admin')));
  Route::resource('cities', 'CitiesController', array('names' => mzk_route_helper('cities', 'admin')));
  Route::resource('services', 'ServicesController', array('names' => mzk_route_helper('services', 'admin')));

  Route::get('businesses/{id}/photos', ['as'=>'admin.businesses.show.photos', 'uses'=>'BusinessesController@getPhotos']);
  Route::post('businesses/{id}/photos', ['as'=>'admin.businesses.save.photos', 'uses'=>'BusinessesController@postPhotos']);
  Route::post('businesses/{id}/bulk/photos', ['as'=>'admin.businesses.save.bulk.photos', 'uses'=>'BusinessesController@postBulkPhotos']);

  Route::post('businesses/{id}/stock/photos', ['as'=>'admin.businesses.save.stock.photo', 'uses'=>'BusinessesController@postStockPhoto']);

  Route::get('businesses/{id}/rate-cards', ['as'=>'admin.businesses.show.rate_cards', 'uses'=>'BusinessesController@getRateCards']);
  Route::post('businesses/{id}/rate-cards', ['as'=>'admin.businesses.save.rate_cards', 'uses'=>'BusinessesController@postRateCards']);

  Route::get('businesses/{id}/services', ['as'=>'admin.businesses.show.services', 'uses'=>'BusinessesController@getServices']);
  Route::post('businesses/{id}/services', ['as'=>'admin.businesses.save.services', 'uses'=>'BusinessesController@postServices']);

  Route::get('businesses/{id}/copy-services', ['as'=>'admin.businesses.copyable.services', 'uses'=>'BusinessesController@getCopyServices']);
  Route::post('businesses/{id}/copy-services', ['as'=>'admin.businesses.copy.services', 'uses'=>'BusinessesController@postCopyServices']);

  Route::get('businesses/{id}/modules', ['as'=>'admin.businesses.show.modules', 'uses'=>'BusinessesController@getModules']);
  Route::post('businesses/{id}/modules', ['as'=>'admin.businesses.save.modules', 'uses'=>'BusinessesController@postModules']);

  Route::get('businesses/{id}/toogle-featured', ['as'=>'admin.businesses.toggle-featured', 'uses'=>'BusinessesController@toggleFeatured']);
  Route::get('businesses/{id}/resluggify', ['as'=>'admin.businesses.resluggify', 'uses'=>'BusinessesController@resluggify']);
  Route::get('businesses/{id}/offers', ['as'=>'admin.businesses.show.offers', 'uses'=>'BusinessesController@getOffers']);
  Route::post('businesses/{id}/offers', ['as'=>'admin.businesses.save.offers', 'uses'=>'BusinessesController@postOffers']);

  Route::get('businesses/{id}/timings', ['as'=>'admin.businesses.get.timings', 'uses'=>'BusinessesController@getTimings']);
  Route::post('businesses/{id}/timings', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postTimings']);
  Route::get('businesses/{id}/location', ['as'=>'admin.businesses.get.location', 'uses'=>'BusinessesController@getLocation']);
  Route::post('businesses/{id}/location', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postLocation']);
  Route::post('businesses/{id}/delete-service', ['as'=>'admin.businesses.services.destroy', 'uses'=>'BusinessesController@deleteOneBusinessService']);

  Route::get('businesses/{id}/generate-old-id', ['as'=>'admin.businesses.generate-old-id', 'uses'=>'BusinessesController@generateOldId']);

});


Route::group(array('prefix'=>'crm'), function(){
  Route::get('/', ['as'=>'crm.dashboard', 'uses'=>'SiteController@crmDashboard']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));


  Route::post('upload-file', ['as'=>'crm.file-upload', 'uses'=>'SiteController@uploadFile']);

  Route::get('businesses/{id}/virtual_numbers/allocate', ['as'=>'admin.virtual_numbers.for.business.allocate',
                                'uses'=>'Virtual_number_allocationsController@getAllocateForBusiness']);
  Route::get('businesses/{id}/virtual_numbers/deallocate', ['as'=>'admin.virtual_numbers.for.business.deallocate',
                                'uses'=>'Virtual_number_allocationsController@deallocate']);
  Route::get('businesses/{id}/virtual_numbers', ['as'=>'admin.businesses.virtual_numbers.show',
                                          'uses'=>'BusinessesController@getVirtualNumberAllocation']);
  Route::get('businesses/{id}/call_logs', ['as'=>'admin.businesses.call_logs',
                                          'uses'=>'Call_logsController@getIndex']);

  Route::get('adverts/get/avalable/slots', ['as'=>'crm.adverts.get.slots', 'uses'=>'AdvertsController@getAvailableSlots']);

  Route::delete('campaigns/adverts/delete/{id}',array('uses' => 'AdvertsController@deleteOne', 'as' => 'admin.adverts.single.destroy'));
  Route::get('campaigns/edit-allocated-slots/{id}', ['as'=>'crm.campaigns.edit.slots', 'uses'=>'CampaignsController@getEditableAverts']);

  Route::resource('adverts', 'AdvertsController', array('names' => mzk_route_helper('adverts', 'admin')));
  Route::resource('campaigns', 'CampaignsController', array('names' => mzk_route_helper('campaigns', 'admin')));
  Route::resource('wikis', 'WikisController', array('names' => mzk_route_helper('wikis', 'admin')));
 
  Route::post('adverts/updatable', ['uses'=>'AdvertsController@updatable', 'as'=>'admin.adverts.updatable']);

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::get('merchants/toggle-leads-access-for-business/{id}', ['as'=>'admin.merchants.toggle_leads_access.businesses', 'uses'=>'MerchantsController@toggleLeadsAccessForBusiness']);
  Route::get('merchants/toggle-resumes-access-for-business/{id}', ['as'=>'admin.merchants.toggle_resumes_access.businesses', 'uses'=>'MerchantsController@toggleResumesAccessForBusiness']);
  Route::get('merchants/toggle-debug-for-business/{id}', ['as'=>'admin.merchants.toggle_debug.businesses', 'uses'=>'BusinessesController@toggleDebug']);


  Route::get('merchants/export', ['as'=>'admin.merchants.export', 'uses'=>'MerchantsController@export']);
  Route::get('merchants/global', ['as'=>'admin.merchants.global', 'uses'=>'MerchantsController@globalIndex']);
  Route::get('merchants/export/global', ['as'=>'admin.merchants.export.global', 'uses'=>'MerchantsController@exportGlobalIndex']);

  Route::get('merchants/access/{merchant_id}/{user_id}', ['as'=>'admin.merchants.access.form', 'uses'=>'MerchantsController@getFormForModuleAccess']);
  Route::post('merchants/access/post', ['as'=>'admin.merchants.access', 'uses'=>'MerchantsController@postModuleAccess']);

  Route::get('merchants/get-potential-clients', ['as'=>'admin.merchants.potential.clients', 'uses'=>'MerchantsController@getUsersForMerchant']);
  Route::get('merchants/get-clients-outlets', ['as'=>'admin.merchants.client.outlets', 'uses'=>'MerchantsController@getOutletsForMerchant']);
  Route::resource('merchants', 'MerchantsController', array('names' => mzk_route_helper('merchants', 'admin')));

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));

  Route::resource('virtual_numbers', 'Virtual_numbersController', array('names' => mzk_route_helper('virtual_numbers', 'admin')));

});

  Route::get('session', function() {
      return Session::all();
  });

  Route::get('/welcome', function () {
    return view('welcome');
  });
  Route::get('/', 'SiteController@index');

  Route::get('/change/locale/{id}', ['uses'=>'SiteController@changeLocale', 'as'=>'change.locale']);
  Route::get('/auth/logout', ['as'=>'users.logout', 'uses'=>'SiteController@logout']);
});
  
});

app/Models/Highlight.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Eloquent;

use Cviebrock\EloquentSluggable\Sluggable;


class Highlight extends Eloquent{
  protected $guarded = array();
  use Sluggable;

  public function sluggable()
  {
      return [
          'slug' => [
              'source' => 'name'
          ]
      ];
  }


  public function __construct(){
    parent::__construct();
    $this->table = 'api_highlights';
  }

  public static $rules = [
    'description'=>'required',
    'name'=>'required',
    'state'=>'required',
  ];

  public $fields = array('description','created_at','updated_at','name','slug','css','business_count','state','old_id',);

  public $fillables = array('description','created_at','updated_at','name','slug','css','business_count','state','old_id',);

  public function isActive(){
    return $this->state == 'active' ? true : false;
  }

}

app/Http/Controllers/HighlightsController.php
<?php
namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Validator;


class HighlightsController extends Controller {

	/**
	 * Highlight Repository
	 *
	 * @var Highlight
	 */
	protected $highlight;

	public function __construct(\App\Models\Highlight $highlight)
	{
		$this->highlight = $highlight;
	}


	public function index()
	{
		$highlights = $this->highlight->all();

		//$this->layout = view('layouts.admin');
    return   view('highlights.index', compact('highlights'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//$this->layout = view('layouts.admin');
    return   view('highlights.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, \App\Models\Highlight::$rules);

		if ($validation->passes())
		{
			$highlight = $this->highlight->create($input);
			
			return redirect()->route('admin.highlights.index');
		}

		return redirect()->route('admin.highlights.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$highlight = $this->highlight->findOrFail($id);

		//$this->layout = view('layouts.admin');
    return   view('highlights.show', compact('highlight'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$highlight = $this->highlight->find($id);

		if (is_null($highlight))
		{
			return redirect()->route('admin.highlights.index');
		}

		//$this->layout = view('layouts.admin');
    return   view('highlights.edit', compact('highlight'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, \App\Models\Highlight::$rules);

		if ($validation->passes())
		{
			$highlight = $this->highlight->find($id);
			$highlight->update($input);

			return redirect()->route('admin.highlights.index');
		}

		return redirect()->route('admin.highlights.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->highlight->find($id)->delete();

		return redirect()->route('admin.highlights.index');
	}

}

resources/views/highlights/create.blade.php
@extends('layouts.panel-content')
@section('content')
<section class="content-header">
  <h1>
    Create Highlight
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Highlights</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-md-12">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
              </ul>
            </div>
          @endif
        </div>
      </div>

{{ Form::open(array('route' => 'admin.highlights.store', 'class' => 'form-horizontal')) }}

        <div class="form-group">
            {{ Form::label('name', 'Name:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('name', Input::old('name'), array('class'=>'form-control', 'placeholder'=>'Name')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('slug', 'Slug:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('slug', Input::old('slug'), array('class'=>'form-control', 'placeholder'=>'Slug')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('description', 'Description:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::textarea('description', Input::old('description'), array('class'=>'form-control', 'placeholder'=>'Description')) }}
            </div>
        </div>

  <div class="form-group">
    {{ Form::label('state', 'Active:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::select('state', ['active'=>'Active', 'inactive'=>'Inactive'], Input::old('state'), 
                               array('class'=>'form-control')) }}
    </div>
  </div>

<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Create', array('class' => 'btn btn-lg btn-primary')) }}
    </div>
</div>

{{ Form::close() }}

</div>
</div>
</section>

@stop

resources/views/highlights/edit.blade.php
@extends('layouts.panel-content')
@section('content')
<section class="content-header">
  <h1>
    Edit Highlight
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Highlights</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-md-12">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
              </ul>
            </div>
          @endif
        </div>
      </div>
{{ Form::model($highlight, array('class' => 'form-horizontal', 'method' => 'PATCH', 'route' => array('admin.highlights.update', $highlight->id))) }}

  <div class="form-group">
    {{ Form::label('name', 'Name:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::text('name', Input::old('name'), array('class'=>'form-control', 'placeholder'=>'Name')) }}
    </div>
  </div>

  <div class="form-group">
    {{ Form::label('slug', 'Slug:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::text('slug', Input::old('slug'), array('class'=>'form-control', 'placeholder'=>'Slug')) }}
    </div>
  </div>

  <div class="form-group">
      {{ Form::label('description', 'Description:', array('class'=>'col-md-2 control-label')) }}
      <div class="col-sm-10">
        {{ Form::textarea('description', Input::old('description'), array('class'=>'form-control', 'placeholder'=>'Description')) }}
      </div>
  </div>

  <div class="form-group">
      {{ Form::label('css', 'Css Class:', array('class'=>'col-md-2 control-label')) }}
      <div class="col-sm-10">
        {{ Form::text('css', Input::old('css'), array('class'=>'form-control', 'placeholder'=>'Css')) }}
      </div>
  </div>
  <div class="form-group">
    {{ Form::label('state', 'Active:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::select('state', ['active'=>'Active', 'inactive'=>'Inactive'], 
                        ($highlight->isActive()?'active':'inactive'), 
                         array('class'=>'form-control')) }}
    </div>
  </div>

<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Update', array('class' => 'btn btn-lg btn-primary')) }}
      {{ link_to_route('admin.highlights.show', 'Cancel', $highlight->id, array('class' => 'btn btn-lg btn-default')) }}
    </div>
</div>

{{ Form::close() }}
</div>
</div>
</section>
@stop

resources/views/highlights/index.blade.php
@extends('layouts.panel-content')
@section('content')
<section class="content-header">
  <h1>All Highlights</h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Highlights</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-md-12">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
              </ul>
            </div>
          @endif
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="well">
          <p>{{ link_to_route('admin.highlights.create', 'Add New Highlight', null, array('class' => 'btn btn-lg btn-success')) }}</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">



@if ($highlights->count())
	<table class="table table-striped">
		<thead>
			<tr>
        <th>ID</th>
				<th>Name</th>
				<th>Slug</th>
				<th>Description</th>
        <th> </th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			@foreach ($highlights as $highlight)
				<tr>
          <td>{{ $highlight->id }}</td>
					<td>{{ $highlight->name }}</td>
					<td>{{ $highlight->slug }}</td>
					<td>{{ $highlight->description }}</td>
          <td>{!! $highlight->isActive()?'<span class="label label-success">ACTIVE</span>':'<span class="label label-default">INACTIVE</span>' !!} </td>
          <td>
            {{ Form::open(array('style' => 'display: inline-block;',  'method' => 'DELETE', 'route' => array('admin.highlights.destroy', $highlight->id))) }}
              {{ Form::submit('Delete', array('class' => 'btn btn-xs btn-danger')) }}
            {{ Form::close() }}
            {{ link_to_route('admin.highlights.edit', 'Edit', array($highlight->id), array('class' => 'btn btn-xs btn-info')) }}
          </td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no highlights
@endif
</div>
</div>
</div>
</div>
</section>
@stop

resources/views/highlights/show.blade.php
@extends('layouts.admin-content')
@section('content')

<h1>Show Highlight</h1>

<p>{{ link_to_route('admin.highlights.index', 'Return to All highlights', null, array('class'=>'btn btn-lg btn-primary')) }}</p>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Slug</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{{ $highlight->name }}}</td>
			<td>{{{ $highlight->slug }}}</td>
			<td>{{{ $highlight->description }}}</td>
      <td>
        {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('admin.highlights.destroy', $highlight->id))) }}
            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
        {{ Form::close() }}
        {{ link_to_route('admin.highlights.edit', 'Edit', array($highlight->id), array('class' => 'btn btn-info')) }}
      </td>
		</tr>
	</tbody>
</table>

@stop