routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {
    Route::get('/auth/login', 'SiteController@login');

Route::group(['middleware'=>['restrict.access']], function(){

  Route::group(array('prefix'=>'sms' ), function(){
    Route::get('/', ['as'=>'admin.sms.index', 'uses'=>'SmsController@index']);
    Route::get('send', ['as'=>'admin.sms.get', 'uses'=>'SmsController@getSend']);
    Route::post('send', ['as'=>'admin.sms.post', 'uses'=>'SmsController@postSend']);
  });


Route::group(array('prefix'=>'content'), function(){
  Route::get('/', ['as'=>'content.dashboard', 'uses'=>'SiteController@contentDashboard']);
  Route::resource('businesses', 'BusinessesController', array('names' => mzk_route_helper('businesses', 'admin')));
  Route::resource('groups', 'GroupsController', array('names' => mzk_route_helper('groups', 'admin')));
  Route::resource('categories', 'CategoriesController', array('names' => mzk_route_helper('categories', 'admin')));
  Route::resource('zones', 'ZonesController', array('names' => mzk_route_helper('zones', 'admin')));
  Route::resource('highlights', 'HighlightsController', array('names' => mzk_route_helper('highlights', 'admin')));
  Route::resource('cities', 'CitiesController', array('names' => mzk_route_helper('cities', 'admin')));
  Route::resource('services', 'ServicesController', array('names' => mzk_route_helper('services', 'admin')));

  Route::get('businesses/{id}/photos', ['as'=>'admin.businesses.show.photos', 'uses'=>'BusinessesController@getPhotos']);
  Route::post('businesses/{id}/photos', ['as'=>'admin.businesses.save.photos', 'uses'=>'BusinessesController@postPhotos']);
  Route::post('businesses/{id}/bulk/photos', ['as'=>'admin.businesses.save.bulk.photos', 'uses'=>'BusinessesController@postBulkPhotos']);

  Route::post('businesses/{id}/stock/photos', ['as'=>'admin.businesses.save.stock.photo', 'uses'=>'BusinessesController@postStockPhoto']);

  Route::get('businesses/{id}/rate-cards', ['as'=>'admin.businesses.show.rate_cards', 'uses'=>'BusinessesController@getRateCards']);
  Route::post('businesses/{id}/rate-cards', ['as'=>'admin.businesses.save.rate_cards', 'uses'=>'BusinessesController@postRateCards']);

  Route::get('businesses/{id}/services', ['as'=>'admin.businesses.show.services', 'uses'=>'BusinessesController@getServices']);
  Route::post('businesses/{id}/services', ['as'=>'admin.businesses.save.services', 'uses'=>'BusinessesController@postServices']);

  Route::get('businesses/{id}/copy-services', ['as'=>'admin.businesses.copyable.services', 'uses'=>'BusinessesController@getCopyServices']);
  Route::post('businesses/{id}/copy-services', ['as'=>'admin.businesses.copy.services', 'uses'=>'BusinessesController@postCopyServices']);

  Route::get('businesses/{id}/modules', ['as'=>'admin.businesses.show.modules', 'uses'=>'BusinessesController@getModules']);
  Route::post('businesses/{id}/modules', ['as'=>'admin.businesses.save.modules', 'uses'=>'BusinessesController@postModules']);

  Route::get('businesses/{id}/toogle-featured', ['as'=>'admin.businesses.toggle-featured', 'uses'=>'BusinessesController@toggleFeatured']);
  Route::get('businesses/{id}/resluggify', ['as'=>'admin.businesses.resluggify', 'uses'=>'BusinessesController@resluggify']);
  Route::get('businesses/{id}/offers', ['as'=>'admin.businesses.show.offers', 'uses'=>'BusinessesController@getOffers']);
  Route::post('businesses/{id}/offers', ['as'=>'admin.businesses.save.offers', 'uses'=>'BusinessesController@postOffers']);

  Route::get('businesses/{id}/timings', ['as'=>'admin.businesses.get.timings', 'uses'=>'BusinessesController@getTimings']);
  Route::post('businesses/{id}/timings', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postTimings']);
  Route::get('businesses/{id}/location', ['as'=>'admin.businesses.get.location', 'uses'=>'BusinessesController@getLocation']);
  Route::post('businesses/{id}/location', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postLocation']);
  Route::post('businesses/{id}/delete-service', ['as'=>'admin.businesses.services.destroy', 'uses'=>'BusinessesController@deleteOneBusinessService']);

  Route::get('businesses/{id}/generate-old-id', ['as'=>'admin.businesses.generate-old-id', 'uses'=>'BusinessesController@generateOldId']);

});


Route::group(array('prefix'=>'crm'), function(){
  Route::get('/', ['as'=>'crm.dashboard', 'uses'=>'SiteController@crmDashboard']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));


  Route::post('upload-file', ['as'=>'crm.file-upload', 'uses'=>'SiteController@uploadFile']);

  Route::get('businesses/{id}/virtual_numbers/allocate', ['as'=>'admin.virtual_numbers.for.business.allocate',
                                'uses'=>'Virtual_number_allocationsController@getAllocateForBusiness']);
  Route::get('businesses/{id}/virtual_numbers/deallocate', ['as'=>'admin.virtual_numbers.for.business.deallocate',
                                'uses'=>'Virtual_number_allocationsController@deallocate']);
  Route::get('businesses/{id}/virtual_numbers', ['as'=>'admin.businesses.virtual_numbers.show',
                                          'uses'=>'BusinessesController@getVirtualNumberAllocation']);
  Route::get('businesses/{id}/call_logs', ['as'=>'admin.businesses.call_logs',
                                          'uses'=>'Call_logsController@getIndex']);

  Route::get('adverts/get/avalable/slots', ['as'=>'crm.adverts.get.slots', 'uses'=>'AdvertsController@getAvailableSlots']);

  Route::delete('campaigns/adverts/delete/{id}',array('uses' => 'AdvertsController@deleteOne', 'as' => 'admin.adverts.single.destroy'));
  Route::get('campaigns/edit-allocated-slots/{id}', ['as'=>'crm.campaigns.edit.slots', 'uses'=>'CampaignsController@getEditableAverts']);

  Route::resource('adverts', 'AdvertsController', array('names' => mzk_route_helper('adverts', 'admin')));
  Route::resource('campaigns', 'CampaignsController', array('names' => mzk_route_helper('campaigns', 'admin')));
  Route::resource('wikis', 'WikisController', array('names' => mzk_route_helper('wikis', 'admin')));
 
  Route::post('adverts/updatable', ['uses'=>'AdvertsController@updatable', 'as'=>'admin.adverts.updatable']);

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::get('merchants/toggle-leads-access-for-business/{id}', ['as'=>'admin.merchants.toggle_leads_access.businesses', 'uses'=>'MerchantsController@toggleLeadsAccessForBusiness']);
  Route::get('merchants/toggle-resumes-access-for-business/{id}', ['as'=>'admin.merchants.toggle_resumes_access.businesses', 'uses'=>'MerchantsController@toggleResumesAccessForBusiness']);
  Route::get('merchants/toggle-debug-for-business/{id}', ['as'=>'admin.merchants.toggle_debug.businesses', 'uses'=>'BusinessesController@toggleDebug']);


  Route::get('merchants/export', ['as'=>'admin.merchants.export', 'uses'=>'MerchantsController@export']);
  Route::get('merchants/global', ['as'=>'admin.merchants.global', 'uses'=>'MerchantsController@globalIndex']);
  Route::get('merchants/export/global', ['as'=>'admin.merchants.export.global', 'uses'=>'MerchantsController@exportGlobalIndex']);

  Route::get('merchants/access/{merchant_id}/{user_id}', ['as'=>'admin.merchants.access.form', 'uses'=>'MerchantsController@getFormForModuleAccess']);
  Route::post('merchants/access/post', ['as'=>'admin.merchants.access', 'uses'=>'MerchantsController@postModuleAccess']);

  Route::get('merchants/get-potential-clients', ['as'=>'admin.merchants.potential.clients', 'uses'=>'MerchantsController@getUsersForMerchant']);
  Route::get('merchants/get-clients-outlets', ['as'=>'admin.merchants.client.outlets', 'uses'=>'MerchantsController@getOutletsForMerchant']);
  Route::resource('merchants', 'MerchantsController', array('names' => mzk_route_helper('merchants', 'admin')));

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));

  Route::resource('virtual_numbers', 'Virtual_numbersController', array('names' => mzk_route_helper('virtual_numbers', 'admin')));

});

  Route::get('session', function() {
      return Session::all();
  });

  Route::get('/welcome', function () {
    return view('welcome');
  });
  Route::get('/', 'SiteController@index');

  Route::get('/change/locale/{id}', ['uses'=>'SiteController@changeLocale', 'as'=>'change.locale']);
  Route::get('/auth/logout', ['as'=>'users.logout', 'uses'=>'SiteController@logout']);
});
  
});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Eloquent;


class Image extends Eloquent {
// implements StaplerableInterface

  protected $guarded = array();
  protected $fillable = [ 'description','name','image_url','image_thumbnail_url',
                          'imagable_id','image_type','image_file_size',
                          'business_id','service_id','slot'];

  public static $rules = [];

  public function __construct(array $attributes = array()) {
    $this->table = 'api_image';
    parent::__construct($attributes);
  }

  public function business(){
    return $this->belongsTo('\App\Models\Business');
  }

  public function getImageThumbnailPathAttribute(){
    return (strstr($this->image_thumbnail_url, 'http') ? '' :'https://s3.amazonaws.com/mazkaracdn').$this->image_thumbnail_url;
  }

  public function getImagePathAttribute(){
    return (strstr($this->image_url, 'http') ? '' :'https://s3.amazonaws.com/mazkaracdn').$this->image_url;
  }

  public function isCover(){
    return $this->image_type == 'cover-image' ? true : false;
  }


  public function upload($file){
    \Image::make($file,array(
      'width' => 300,
      'height' => 300,
      'grayscale' => true
    ))->save('/path/to/the/thumbnail.jpg');
  }

}

resources/views/businesses/create.blade.php
@extends('layouts.panel-content')
@section('content')
<section class="content-header">
  <h1>
    Create Business
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Business</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-2">
          @include('businesses.form')
        </div>
      </div>
    </div>
  </div>
</section>
@stop

resources/views/businesses/edit.blade.php
@extends('layouts.panel-content')
@section('content')
<section class="content-header">
  <h1>
    Edit Business
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Business</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-2">
          @include('businesses.form')
        </div>
      </div>
    </div>
  </div>
</section>
@stop

resources/views/businesses/index.blade.php
@extends('layouts.panel-content')
@section('content')
<section class="content-header">
  <h1>
    Businesses
    <small>All venues based in {{ mzk_get_current_locale_attrib('name') }}</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Businesses</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-md-12">
        <div class="well">
          {{ link_to_route('admin.businesses.create', 'Add New Business', null, array('class' => 'btn  btn-success')) }}
        </div>


<div class="well">
  {{ Form::open(array('style' => 'display: inline-block;', 'class'=>'form-inline', 'method' => 'GET')) }}

    {{ Form::text('id', Input::get('id'), array('class'=>'form-control col-md-1', 'style'=>'width:50px;', 'placeholder'=>'ID?')) }}
    {{ Form::text('search', Input::get('search'), array('class'=>'form-control col-md-1', 'style'=>'width:150px;', 'placeholder'=>'Search')) }}

    {{ Form::select('zone', ([''=>'Zone?'] + \App\Models\Zone::byLocale()->orderby('name', 'ASC')->pluck('name', 'id')->all()), Input::get('zone'), array('class'=>'form-control ')) }}   
    {{ Form::select('is_featured', ([''=>'featured?', '0'=>'Not featured', '1'=>'Featured']), Input::get('is_featured'), array('class'=>'form-control ')) }}   
    {{ Form::select('is_chain', ([''=>'chain?', '0'=>'Not Chain', '1'=>'Is Chain']), Input::get('is_chain'), array('class'=>'form-control ')) }}   

    {{ Form::select('chain', ([''=>'Chain?'] + \App\Models\Group::byLocale()->orderby('name', 'ASC')->pluck('name', 'id')->all()), Input::get('chain'), array('class'=>'form-control ', 'style'=>'width:175px')) }}   

    {{ Form::select('sort', ([ ''=>'Sort by?', 
                              'idAsc'=>'ID Asc', 
                              'idDesc'=>'ID Desc', 
                              'nameAsc'=>'Name Asc', 
                              'nameDesc'=>'Name Desc', 
                              'lastUpdateAsc'=>'Last Update Asc',
                              'lastUpdateDesc'=>'Last Update Desc',
                              ]),
                           Input::get('sort'), array('class'=>'form-control', 'style'=>'width:100px;', 'placeholder'=>'Service')) }}

    <button type="submit" class="btn btn-default">Filter</button>
  {{ Form::close() }}
</div>







        @if ($businesses->count())
          <div class="list-group">
            @foreach ($businesses as $business)
              <a href="{{ route('admin.businesses.show', array($business->id) ) }}" class="list-group-item " >
                <div class="pull-right">
                  <small>Last Updated {{{ \Carbon\Carbon::parse($business->updated_at)->diffForHumans(\Carbon\Carbon::now()) }}}</small><br/>

                  {!! $business->isFeatured()?'<span class="label label-success">'.$business->is_featured.'</span>':'<span class="label label-danger">NON FEATURED</span>' !!}
                </div>
                <h4 class="list-group-item-heading">
                  {{{ $business->id }}} -          
                  {{{ $business->name }}}
                  <small>
                    <span class="label label-{{ $business->getRichnessColor() }}" >
                      {{ '# '.$business->popularity }}
                    </span>
                  </small>
                </h4>
                <p class="list-group-item-text">
                  <b>Phone:</b>{{{ join(',', $business->phone_number) }}}
                  <b>Email:</b>{{{ join(',', $business->email) }}}
                  <br/>
                  <b>Website:</b>{{{ $business->website }}}
                  <b>Zone:</b>{{{ $business->zone_cache }}}
                </p>
                <p class="list-group-item-text">
                  <span class="label label-{{ $business->active == '1' ?'success':'warning'}}">
                    {{{ $business->active == '1'?'active':'inactive' }}}
                  </span>
                  @if(0 ==($business->latitude + $business->longitude))
                    <span class="label label-danger">Location Not Set</span>
                  @endif
                </p>
              </a>
            @endforeach      
          </div>

          <div class="row">
            <div class="col-md-12">
          {{ $businesses->appends($params)->render() }}
          <div class="pull-right">
            {{ count($businesses) }} / {{ $businesses->total() }} entries
          </div></div>
        </div>
        @else
          There are no businesses
        @endif
      </div>
    </div>
  </div>
</div>
</section>
@stop

resources/views/businesses/modules.blade.php
{{ Form::model($business, array('class' => 'form-horizontal', 
                                'method' => 'POST', 'files'=>true, 
                                'action' => array('BusinessesController@postModules', 
                                                  $business->id))) }}
<section class="content">
  <div class="box box-primary">
    <div class="box-body">
      <div class="row">
        <div class="col-md-10 ">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
              </ul>
            </div>
          @endif
        </div>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Module</th>
            <td>Access</td>
          </tr>
        </thead>
        <tbody>
          @foreach($modules as $module)
            <tr>
              <td>{{ $module->name }}</td>
              <td>{!! Form::select('modules['.$module->id.'][active]', array('0'=>'No Access', '3'=>'Full Access'), 
                        (isset($selected_modules[$module->id])?$selected_modules[$module->id]:0),  array('class'=>'form-control') ) !!}</td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
    </div>
  </div>
</section>
{{ Form::close() }}

resources/views/businesses/offers.blade.php
@extends('layouts.panel-content')
@section('content')
<style type="text/css">
.btn-default.active, .btn-default:hover
{
color: #fff;
background-color: #449d44;
border-color: #398439;
}
</style>
<section class="content-header">
  <h1>
    {{$business->name}} Offers
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Business</li>
  </ol>
</section>
{{ Form::model($business, array('class' => 'form-horizontal', 'method' => 'POST', 'files'=>true, 'action' => array('BusinessesController@postOffers', $business->id))) }}
<section class="content">
  <div class="box box-primary">
    <div class="box-body">
      <div class="row">
        <div class="col-md-12">

          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
              </ul>
            </div>
          @endif

          <div class="form-group">
            <div class="col-sm-12">
              <fieldset>
                  <a style="margin:10px 0px;" href="javascript:void(0)" class="btn btn-success" id="lnk-add-offer">Add Offer(s)</a>
                  <hr/>
                  <div id="offers-here"></div>
                  @if(isset($business))
                      @foreach($business->details->offers as $offer)
                          @include('businesses.partials.offer')
                          <?php unset($offer);?>
                      @endforeach
                  @endif
              </fieldset>

            </div>
          </div>

        </div>
      </div>
    </div>
    <div class="box-footer">
          <div class="form-group">
              <div class="col-sm-12">
                {{ Form::submit('Save', array('class' => 'btn  btn-primary')) }}
        {{ link_to_route('admin.businesses.show', 'Cancel', array($business->id), array('class' => 'btn btn-warning')) }}

              </div>
          </div>



    </div>
  </div>
</section>
{{ Form::close() }}
<div id="offer_holder"  style="display:none" >@include('businesses.partials.offer')</div>


<script>
$(function(){

    $(document).on('click', '.toggles .btn', function(){
      inp = $(this).find('input');
      hd = $(this).parents('.toggles').first().find('input:hidden');
      ctVal = $(hd).val();
      if(!$(this).hasClass('active')){
        $(hd).val( $(hd).val() + $(inp).val() );
      }else{
        $(hd).val(ctVal.replace('/'+$(inp).val()+'/g', ''));
      }
    });

    $('#lnk-add-offer').click(function(){
      html = $('#offer_holder').html();
      nm = new Date().getTime();
      html = html.replace(/_REPLACE_/g, nm);
      console.log(html);
      $('#offers-here').prepend(html);
    });


    $(document).on('click', '.content .delete', function(){
      $(this).parents('.row-content').first().remove();
    });

});

</script>
@stop

resources/views/businesses/photos.blade.php
@extends('layouts.panel-content')
@section('content')

<section class="content-header">
  <h1>
    {{$business->name}} Photos
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Business</li>
  </ol>
</section>
{{ Form::model($business, array('class' => 'form-horizontal', 
                                'method' => 'POST', 'files'=>true, 
                                'action' => array('BusinessesController@postPhotos', 
                                                  $business->id))) }}

<section class="content">
  <div class="box box-primary">
    <div class="box-body">
      <div class="row">
        <div class="col-md-10 ">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
              </ul>
            </div>
          @endif
        </div>
      </div>
      <div class="row">
        @foreach($business->photos()->orderby('slot', 'asc')->get() as $photo)
          <div class="image-content col-md-3">
            <div class="row">
              <div class="col-md-12">
                <img src="{{ $photo->image_thumbnail_path }}" class="img-thumbnail" />
              </div>
            </div>
            <div class="well">
            <div class="row">
              <div class="col-md-3">
                COVER?
                    {{ Form::radio("is_cover", $photo->id, $photo->isCover(), array('style'=>'display:inline')) }}
              </div>
              <div class="col-md-5">
              {{ Form::text("orderables[$photo->id]", $photo->sort, array('class'=>'form-control', 'placeholder'=>'Order') ) }}
              </div>
              <div class="col-md-1">
                {{ Form::checkbox("deletablePhotos[]", $photo->id, false, array('style'=>'display:none;', 'class'=>'deletable') ) }}
                <a href="javascript:void(0)" class="mr5 delete-existing btn btn-sm btn-danger">
                  <i class="fa fa-times"></i>
                </a>
              </div>
            </div>
            </div>

          </div>
        @endforeach
      </div>
      <div class="row">
        <div class="col-sm-10 ">
          {{ Form::file('images[]', array( 'accept'=>"image/*", 'id'=>'input-bulk-image-upload', 'multiple'=>'true')) }}
        </div>
      </div>
    </div>
    <div class="box-footer">
      {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
      {{ link_to_route('admin.businesses.show', 'Cancel', array($business->id), array('class' => 'btn btn-warning ')) }}
    </div>
  </div>
</section>
{{ Form::close() }}


{{ Form::model($business, array('class' => 'form-horizontal', 
                                'method' => 'POST', 'files'=>true, 
                                'action' => array('BusinessesController@postStockPhoto', 
                                                  $business->id))) }}

<section class="content">
  <div class="box box-primary">
    <div class="box-header">
      <h3>Stock Photo Cover?</h3>
    </div>
    <div class="box-body">
      <div class="row">
        @foreach(\App\Models\Business::getStockPhotos() as $opt)
          <div class="col-md-2">
            <img src="{{ mzk_assets('assets/stock/'.$opt.'.jpg') }}" class="img-thumbnail" height="100" />
            {{ Form::radio('cover_image', $opt, ($business->getCoverImageUrl() == $opt)) }}
            {{$opt}}
          </div>
        @endforeach
      </div>
    </div>
    <div class="box-footer">
      {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
      {{ link_to_route('admin.businesses.show', 'Cancel', array($business->id), array('class' => 'btn btn-warning ')) }}
    </div>
  </div>
</section>
{{ Form::close() }}

<script type="text/javascript">
  $(document).on('click', '.delete-existing', function(){
    $(this).parents('.image-content').first().hide();
    $(this).parents('.image-content').first().find('.deletable').prop('checked', true);
  });

</script>
@stop

resources/views/businesses/rate-cards.blade.php
@extends('layouts.panel-content')
@section('content')

<section class="content-header">
  <h1>
    {{$business->name}} Rate Cards
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Business</li>
  </ol>
</section>
{{ Form::model($business, array('class' => 'form-horizontal', 
                                'method' => 'POST', 'files'=>true, 
                                'action' => array('BusinessesController@postRateCards', 
                                                  $business->id))) }}

<section class="content">
  <div class="box box-primary">
    <div class="box-body">
      <div class="row">
        <div class="col-md-10 ">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                {{ implode('', $errors->all('<li class="error">:message</li>')) }}
              </ul>
            </div>
          @endif
        </div>
      </div>
      <div class="row">
        @foreach($business->rateCards()->orderby('slot', 'asc')->get() as $photo)

          <div class="image-content col-md-3">
            <div class="row">
              <div class="col-md-12">
                <img src="{{ $photo->image_thumbnail_path }}" class="img-thumbnail" />
              </div>
            </div>
            <div class="well">
            <div class="row">
              <div class="col-md-9">
              {{ Form::text("orderables[$photo->id]", $photo->slot, array('class'=>'form-control') ) }}
              </div>
              <div class="col-md-2">
                {{ Form::checkbox("deletablePhotos[]", $photo->id, false, array('style'=>'display:none;', 'class'=>'deletable') ) }}
                <a href="javascript:void(0)" class="mr5 delete-existing btn btn-sm btn-danger">
                  <i class="fa fa-times"></i>
                </a>
              </div>
            </div>
            </div>

          </div>
        @endforeach
      </div>
      <div class="row">
        <div class="col-sm-10 ">
          {{ Form::file('images[]', array( 'accept'=>"image/*", 'id'=>'input-bulk-image-upload', 'multiple'=>'true')) }}
        </div>
      </div>
    </div>
    <div class="box-footer">
      {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
      {{ link_to_route('admin.businesses.show', 'Cancel', array($business->id), array('class' => 'btn btn-warning ')) }}
    </div>
  </div>
</section>
{{ Form::close() }}

<script type="text/javascript">
  $(document).on('click', '.delete-existing', function(){
    $(this).parents('.image-content').first().hide();
    $(this).parents('.image-content').first().find('.deletable').prop('checked', true);
  });

</script>
@stop

resources/views/businesses/timings.blade.php
@extends('layouts.panel-content')
@section('content')
<style type="text/css">
.btn-default.active, .btn-default:hover
{
color: #fff;
background-color: #449d44;
border-color: #398439;
}
</style>
<section class="content-header">
  <h1>
    {{$business->name}} Timings
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/content">Content</a></li>
    <li class="active">Business</li>
  </ol>
</section>

        @include('businesses.partials.timings')

@stop