routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {
    Route::get('/auth/login', 'SiteController@login');

Route::group(['middleware'=>['restrict.access']], function(){

  Route::group(array('prefix'=>'sms' ), function(){
    Route::get('/', ['as'=>'admin.sms.index', 'uses'=>'SmsController@index']);
    Route::get('send', ['as'=>'admin.sms.get', 'uses'=>'SmsController@getSend']);
    Route::post('send', ['as'=>'admin.sms.post', 'uses'=>'SmsController@postSend']);
  });


Route::group(array('prefix'=>'content'), function(){
  Route::get('/', ['as'=>'content.dashboard', 'uses'=>'SiteController@contentDashboard']);
  Route::resource('businesses', 'BusinessesController', array('names' => mzk_route_helper('businesses', 'admin')));
  Route::resource('groups', 'GroupsController', array('names' => mzk_route_helper('groups', 'admin')));
  Route::resource('categories', 'CategoriesController', array('names' => mzk_route_helper('categories', 'admin')));
  Route::resource('zones', 'ZonesController', array('names' => mzk_route_helper('zones', 'admin')));
  Route::resource('highlights', 'HighlightsController', array('names' => mzk_route_helper('highlights', 'admin')));
  Route::resource('cities', 'CitiesController', array('names' => mzk_route_helper('cities', 'admin')));
  Route::resource('services', 'ServicesController', array('names' => mzk_route_helper('services', 'admin')));

  Route::get('businesses/{id}/photos', ['as'=>'admin.businesses.show.photos', 'uses'=>'BusinessesController@getPhotos']);
  Route::post('businesses/{id}/photos', ['as'=>'admin.businesses.save.photos', 'uses'=>'BusinessesController@postPhotos']);
  Route::post('businesses/{id}/bulk/photos', ['as'=>'admin.businesses.save.bulk.photos', 'uses'=>'BusinessesController@postBulkPhotos']);

  Route::post('businesses/{id}/stock/photos', ['as'=>'admin.businesses.save.stock.photo', 'uses'=>'BusinessesController@postStockPhoto']);

  Route::get('businesses/{id}/rate-cards', ['as'=>'admin.businesses.show.rate_cards', 'uses'=>'BusinessesController@getRateCards']);
  Route::post('businesses/{id}/rate-cards', ['as'=>'admin.businesses.save.rate_cards', 'uses'=>'BusinessesController@postRateCards']);

  Route::get('businesses/{id}/services', ['as'=>'admin.businesses.show.services', 'uses'=>'BusinessesController@getServices']);
  Route::post('businesses/{id}/services', ['as'=>'admin.businesses.save.services', 'uses'=>'BusinessesController@postServices']);

  Route::get('businesses/{id}/copy-services', ['as'=>'admin.businesses.copyable.services', 'uses'=>'BusinessesController@getCopyServices']);
  Route::post('businesses/{id}/copy-services', ['as'=>'admin.businesses.copy.services', 'uses'=>'BusinessesController@postCopyServices']);

  Route::get('businesses/{id}/modules', ['as'=>'admin.businesses.show.modules', 'uses'=>'BusinessesController@getModules']);
  Route::post('businesses/{id}/modules', ['as'=>'admin.businesses.save.modules', 'uses'=>'BusinessesController@postModules']);

  Route::get('businesses/{id}/toogle-featured', ['as'=>'admin.businesses.toggle-featured', 'uses'=>'BusinessesController@toggleFeatured']);
  Route::get('businesses/{id}/resluggify', ['as'=>'admin.businesses.resluggify', 'uses'=>'BusinessesController@resluggify']);
  Route::get('businesses/{id}/offers', ['as'=>'admin.businesses.show.offers', 'uses'=>'BusinessesController@getOffers']);
  Route::post('businesses/{id}/offers', ['as'=>'admin.businesses.save.offers', 'uses'=>'BusinessesController@postOffers']);

  Route::get('businesses/{id}/timings', ['as'=>'admin.businesses.get.timings', 'uses'=>'BusinessesController@getTimings']);
  Route::post('businesses/{id}/timings', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postTimings']);
  Route::get('businesses/{id}/location', ['as'=>'admin.businesses.get.location', 'uses'=>'BusinessesController@getLocation']);
  Route::post('businesses/{id}/location', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postLocation']);
  Route::post('businesses/{id}/delete-service', ['as'=>'admin.businesses.services.destroy', 'uses'=>'BusinessesController@deleteOneBusinessService']);

  Route::get('businesses/{id}/generate-old-id', ['as'=>'admin.businesses.generate-old-id', 'uses'=>'BusinessesController@generateOldId']);

});


Route::group(array('prefix'=>'crm'), function(){
  Route::get('/', ['as'=>'crm.dashboard', 'uses'=>'SiteController@crmDashboard']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));


  Route::post('upload-file', ['as'=>'crm.file-upload', 'uses'=>'SiteController@uploadFile']);

  Route::get('businesses/{id}/virtual_numbers/allocate', ['as'=>'admin.virtual_numbers.for.business.allocate',
                                'uses'=>'Virtual_number_allocationsController@getAllocateForBusiness']);
  Route::get('businesses/{id}/virtual_numbers/deallocate', ['as'=>'admin.virtual_numbers.for.business.deallocate',
                                'uses'=>'Virtual_number_allocationsController@deallocate']);
  Route::get('businesses/{id}/virtual_numbers', ['as'=>'admin.businesses.virtual_numbers.show',
                                          'uses'=>'BusinessesController@getVirtualNumberAllocation']);
  Route::get('businesses/{id}/call_logs', ['as'=>'admin.businesses.call_logs',
                                          'uses'=>'Call_logsController@getIndex']);

  Route::get('adverts/get/avalable/slots', ['as'=>'crm.adverts.get.slots', 'uses'=>'AdvertsController@getAvailableSlots']);

  Route::delete('campaigns/adverts/delete/{id}',array('uses' => 'AdvertsController@deleteOne', 'as' => 'admin.adverts.single.destroy'));
  Route::get('campaigns/edit-allocated-slots/{id}', ['as'=>'crm.campaigns.edit.slots', 'uses'=>'CampaignsController@getEditableAverts']);

  Route::resource('adverts', 'AdvertsController', array('names' => mzk_route_helper('adverts', 'admin')));
  Route::resource('campaigns', 'CampaignsController', array('names' => mzk_route_helper('campaigns', 'admin')));
  Route::resource('wikis', 'WikisController', array('names' => mzk_route_helper('wikis', 'admin')));
 
  Route::post('adverts/updatable', ['uses'=>'AdvertsController@updatable', 'as'=>'admin.adverts.updatable']);

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::get('merchants/toggle-leads-access-for-business/{id}', ['as'=>'admin.merchants.toggle_leads_access.businesses', 'uses'=>'MerchantsController@toggleLeadsAccessForBusiness']);
  Route::get('merchants/toggle-resumes-access-for-business/{id}', ['as'=>'admin.merchants.toggle_resumes_access.businesses', 'uses'=>'MerchantsController@toggleResumesAccessForBusiness']);
  Route::get('merchants/toggle-debug-for-business/{id}', ['as'=>'admin.merchants.toggle_debug.businesses', 'uses'=>'BusinessesController@toggleDebug']);


  Route::get('merchants/export', ['as'=>'admin.merchants.export', 'uses'=>'MerchantsController@export']);
  Route::get('merchants/global', ['as'=>'admin.merchants.global', 'uses'=>'MerchantsController@globalIndex']);
  Route::get('merchants/export/global', ['as'=>'admin.merchants.export.global', 'uses'=>'MerchantsController@exportGlobalIndex']);

  Route::get('merchants/access/{merchant_id}/{user_id}', ['as'=>'admin.merchants.access.form', 'uses'=>'MerchantsController@getFormForModuleAccess']);
  Route::post('merchants/access/post', ['as'=>'admin.merchants.access', 'uses'=>'MerchantsController@postModuleAccess']);

  Route::get('merchants/get-potential-clients', ['as'=>'admin.merchants.potential.clients', 'uses'=>'MerchantsController@getUsersForMerchant']);
  Route::get('merchants/get-clients-outlets', ['as'=>'admin.merchants.client.outlets', 'uses'=>'MerchantsController@getOutletsForMerchant']);
  Route::resource('merchants', 'MerchantsController', array('names' => mzk_route_helper('merchants', 'admin')));

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));

  Route::resource('virtual_numbers', 'Virtual_numbersController', array('names' => mzk_route_helper('virtual_numbers', 'admin')));

});

  Route::get('session', function() {
      return Session::all();
  });

  Route::get('/welcome', function () {
    return view('welcome');
  });
  Route::get('/', 'SiteController@index');

  Route::get('/change/locale/{id}', ['uses'=>'SiteController@changeLocale', 'as'=>'change.locale']);
  Route::get('/auth/logout', ['as'=>'users.logout', 'uses'=>'SiteController@logout']);
});
  
});

app/Models/Merchant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Eloquent;




class Merchant extends Eloquent
{
  protected $guarded = array();

  public function __construct(){
    parent::__construct();
    $this->table = 'api_merchant';
  }

  public static $rules = ['name'=>'required','email'=>'required','phone'=>'required'];


  public static $fields = array( 'description','name','ref','email','phone','global_id','old_id','city_id');

  public  $fillable = array( 'description','name','ref','email','phone','global_id','old_id','city_id');
  
  public function scopeByLocale($query, $locale = false){
    $locale = $locale == false ? mzk_get_localeID() : $locale;
    return $query->where('city_id', '=', $locale);
  }
  
  public function getDisplayableAttribute(){
    return $this->id.' - '.$this->name;
  }


  public function users(){
    return $this->belongsToMany('App\Models\User', 'api_merchantuser', 'merchant_id', 'user_id')
                    ->withPivot('role')->where('api_merchantuser.role', '=', 'merchant'); 
  }

  public function pocs(){
    return $this->belongsToMany('App\Models\User', 'api_merchantuser', 'merchant_id', 'user_id')
                  ->withPivot('role')->where('api_merchantuser.role', '=', 'poc'); 
  }


  public function generateGlobalID(){
    $str = 'FB'.str_pad($this->id, 10, "0", STR_PAD_LEFT);
    $this->global_id = $str;
    $this->save();
  }

  public function getDisplayableMerchantID(){
    return $this->global_id;
    
    $str = 'FB'.str_pad($this->id, 10, "0", STR_PAD_LEFT);
    return $str;
  }

  public function poc(){
    return $this->pocs()->get()->count()>0 ? $this->pocs()->get()->first():false;
  }

  public function pocId(){
    return $this->poc() ? $this->poc()->id:'';
  }

  public function businesses(){
    return $this->hasMany('App\Models\Business'); 
  }

  public function allocateUsers($user_ids){

    if(is_null($user_ids)){
      return false;
    }

    if(!is_array($user_ids)){
      $user_ids = [$user_ids];
    }
    $data = [];
    foreach($user_ids as $user_id){
      $data[$user_id] = ['role'=>'merchant'];
    }



    $this->users()->sync($data);

    foreach($this->users as $user){
      $role = Role::where('name', '=', 'client')->first();
      $user->attachRole($role);
      $user->save();
    }
  }


    public function allocateUsersNPocs($user_ids, $pocs){

    if(is_null($user_ids)){
      $user_ids = [];
      // deallocate current allocated users
      foreach($this->users as $user){
        if($user->hasTheRoles('client')){
          $user->detachTheRoles('client');
          $user->save();
        }
      }
    }

    if(!is_array($user_ids)){
      $user_ids = [$user_ids];
    }

    if(!is_array($pocs)){
      $pocs = [$pocs];
    }

    $data = [];
    foreach($user_ids as $user_id){
      $data[$user_id] = ['role'=>'merchant'];
    }
    foreach($pocs as $user_id){
      $data[$user_id] = ['role'=>'poc'];
    }

    $this->users()->sync($data);

    foreach($this->users as $user){
      $user->attachTheRoles('client');
      $user->save();
    }
  }


  public function deletePre(){
    $this->pocs()->detach();
    $this->users()->detach();
    $existing_business_ids = $this->businesses()->pluck('id', 'id')->all();
    \DB::table('api_business')->whereIn('id', $existing_business_ids)->update(['merchant_id'=>null]);

    $this->save();
  }



  public function allocatePOCs($user_ids){

    if(is_null($user_ids)){
      return false;
    }

    if(!is_array($user_ids)){
      $user_ids = [$user_ids];
    }

    $data = [];
    foreach($user_ids as $user_id){
      $data[$user_id] = ['role'=>'poc'];
    }

    $this->pocs()->sync($data);
  }



  public function allocateBusinesses($business_ids){
    if(is_null($business_ids)){
      return false;
    }

    if(!is_array($business_ids)){
      $business_ids = [$business_ids];
    }

    $existing_business_ids = $this->businesses()->pluck('id', 'id')->all();

    \DB::table('api_business')->whereIn('id', $existing_business_ids)->update(['merchant_id'=>null]);
    \DB::table('api_business')->whereIn('id', $business_ids)->update(['merchant_id'=>$this->id]);

    //$this->businesses()->sync($business_ids);
  }

  public function allocateBusinessesNAttributes($businesses){
    if(is_null($businesses)){
      return false;
    }

    $this->businesses()->sync($businesses);
  }

  public function canActivateDeactivateVirtualNumbers(){
    // you can only activate or deactivate virtual numbers when you have them
    return $this->getCountOfVenuesWithVirtualNumbers() > 0 ? true : false;
  }

  public function isAnyVirtualNumberActive(){
    $v = $this->getVenuesWithVirtualNumbers();
    return count($v)>0 ? true : false;
  }


  public function getCountOfVenuesWithVirtualNumbers(){
    $r = $this->getVenuesWithVirtualNumbers();
    return ($r!=false) ? count($r) : 0;
  }

  public function getVenuesWithVirtualNumbers(){
    $businesses = $this->businesses();//->lists('business_id', 'business_id');
    // get list of venues with virtual numbers that are active
    $with_virtual = [];
    foreach($businesses as $business){
      $r = $business->current_virtual_number_allocation();
      if($r!=false){
        $with_virtual[] = $r;
      }
    }

    return $with_virtual;
  }


  public function city_name(){
    return $this->city_id > 0 ? $this->city->name : '';
  }

  public function poc_name(){
    return $this->pocs()->count() > 0 ? $this->pocs()->first()->name : '';
  }


  public function city(){
    return $this->belongsTo('App\Models\City', 'city_id');
  }


  public function scopeBySearch($query, $search){
    return $query->where('name', 'LIKE', '%'.$search.'%');
  }

  public function scopeByVirtualNumber($query, $num){
    $numbers = Virtual_number::query()->bySearch($num)->lists('id','id')->all();
    $allocations = Virtual_number_allocation::select()->byNumbers($numbers)->justActive()->lists('business_id','business_id')->all();
    // find businesses belonging to merchants
    $merchant_ids = \DB::table('business_merchant')->whereIn('business_id', $allocations)->lists('merchant_id','merchant_id');
    return $query->whereIn('id', $merchant_ids);
  }

  public function setCity($locale = false){
    $this->city_id = $locale == false ? mzk_get_localeID() : $locale;
    $this->save();
  }
  




}

resources/views/merchants/partials/business-for-invoice-form.blade.php
  <div class="form-group">
    {{ Form::label('outlets[]', 'Outlet(s):', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-4">
      @foreach($merchant->businesses as $business)
        <p>
          <?php $val = false;?>
          @if(isset($invoice))
          @endif
          {{ Form::checkbox('outlets[]', $business->id, $val, array('class'=>'form-control', 'style'=>'width:10px;display:inline-block;height:10px;')) }}
          {{ $business->name }}, {{ $business->zone_cache }}
          <a target="_blank" href="/{{ MazkaraHelper::getLocale().'/'.$business->slug}}" class="btn btn-xs btn-success"><i class="fa fa-eye"></i></a>
          <a target="_blank" href="/partner/{{$business->id}}" class="btn btn-xs btn-primary"><i class="fa fa-user"></i></a>
        </p>
      @endforeach
    </div>
  </div>

resources/views/merchants/partials/form.blade.php
@if(isset($merchant))
  {{ Form::model($merchant, array('class' => 'form-horizontal', 'method' => 'PATCH', 'route' => array('admin.merchants.update', $merchant->id))) }}
@else
  {{ Form::open(array('route' => 'admin.merchants.store', 'class' => 'form-horizontal')) }}
@endif

<section class="content">
  <div class="box box-primary">
    <div class="box-body">
      <div class="row">
        <div class="col-md-12">

      @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
            {!! implode('', $errors->all('<li class="error">:message</li>')) !!}
          </ul>
        </div>
      @endif
      @if(isset($merchant))
        <div class="form-group">
          {{ Form::label('global_id', 'Global ID:', array('class'=>'col-md-2 control-label')) }}
          <div class="col-sm-10">
            {{ Form::text('global_id', Input::old('global_id'), array('class'=>'form-control', 'placeholder'=>'Global ID')) }}
          </div>
        </div>
      @endif
      <div class="form-group">
        {{ Form::label('name', 'Entity Name:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
          {{ Form::text('name', Input::old('name'), array('class'=>'form-control', 'placeholder'=>'Name')) }}
        </div>
      </div>

      <div class="form-group">
        {{ Form::label('email', 'Email Address:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
          {{ Form::text('email', Input::old('email'), array('class'=>'form-control', 'placeholder'=>'Email Address')) }}
        </div>
      </div>
      <div class="form-group">
        {{ Form::label('phone', 'Phone:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
          {{ Form::text('phone', Input::old('phone'), array('class'=>'form-control', 'placeholder'=>'Phone')) }}
        </div>
      </div>

      <div class="form-group">
          {{ Form::label('users', 'Assigned Users(select):', array('class'=>'col-md-2 control-label')) }}
          <div class="col-sm-10">
            {{ Form::text('users-search', '', array('class'=>'form-control', 'id'=>'user-search', 'placeholder'=>'Type to search for users to allocate')) }}
            <p></p>
            <ul class="list-group" id="users-holder">
              @if(isset($merchant))
                @foreach($merchant->users as $user)
                  @include('merchants.partials.user', ['user'=>$user])
                @endforeach
              @endif
            </ul>
          </div>
      </div>

      <div class="form-group">
          {{ Form::label('businesses', 'Assigned Venues:', array('class'=>'col-md-2 control-label')) }}
          <div class="col-sm-10">
            {{ Form::text('businesses-search', '', array('class'=>'form-control', 'id'=>'business-search', 'placeholder'=>'Type to search for venue to allocate')) }}
            <p></p>
            <ul class="list-group" id="businesses-holder">
              @if(isset($merchant))
                @foreach($merchant->businesses as $business)
                  @include('merchants.partials.business', ['business'=>$business])
                @endforeach
              @endif
            </ul>
          </div>
      </div>

      <div class="form-group">
        {{ Form::label('sales_admins', 'Sales POC:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
          {{ Form::select('sales_admins[]', \App\Models\User::select()->byRoles(['admin', 'sales-admin', 'sales'])
                                                ->get()
                                                ->pluck('selectable_full_name', 'id')
                                                ->all(), 
                                                isset($merchant)?$merchant->pocId():'', 
                                                array('class'=>'form-control')) }}
        </div>
      </div>
      <div class="form-group">
        {{ Form::label('tan', 'TAN:', array('class'=>'col-md-2 control-label')) }}
        <div class="col-sm-10">
          {{ Form::text('tan', Input::old('tan'), array('class'=>'form-control', 'placeholder'=>'TAN')) }}
        </div>
      </div>
</div>
</div>
</div>
<div class="box-footer">
      <div class="form-group">
          <label class="col-sm-2 control-label">&nbsp;</label>
          <div class="col-sm-10">
            {{ Form::submit('Save', array('class' => 'btn btn-lg btn-primary')) }}
            @if(isset($merchant))
              {{ link_to_route('admin.merchants.show', 'Cancel', $merchant->id, array('class' => 'btn btn-lg btn-default')) }}
            @endif
          </div>
      </div>
</div>
</div>
</section>
{{ Form::close() }}
<script type="text/javascript">
$(function(){
  $('#user-search').autocomplete({
    source:'/crm/merchants/get-potential-clients',
    select: function(event, ui){
      $('#users-holder').append(ui.item.html);
    },
  }).autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( '<div >' + item.id + ' - ' +item.name + '<small>('+item.email+')</small></div>')
      .appendTo( ul );
  };
  $('#business-search').autocomplete({
    source:'/crm/merchants/get-clients-outlets',
    select: function(event, ui){
      $('#businesses-holder').append(ui.item.html);
    },
  }).autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( '<div >' + item.id + ' - ' +item.name + '<small>('+item.zone_cache+')</small></div>' )
      .appendTo( ul );
  };  

  $(document).on('click', '.deletable-link', function(){
    $(this).prevAll('.deletable').first().attr('checked', true);
    $(this).parents('li').first().css('backgroundColor', 'red').fadeOut( "slow", function() {
      $(this).remove();
    });
  });


});
</script>

resources/views/merchants/partials/form.old.blade.php
        @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
          </div>
        @endif

@if(isset($merchant))
  {{ Form::model($merchant, array('class' => 'form-horizontal', 'method' => 'PATCH', 'route' => array('admin.merchants.update', $merchant->id))) }}
  <div class="form-group">
      {{ Form::label('global_id', 'Global ID:', array('class'=>'col-md-2 control-label')) }}
      <div class="col-sm-10">
        {{ Form::text('global_id', Input::old('global_id'), array('class'=>'form-control', 'placeholder'=>'Global ID')) }}
      </div>
  </div>

@else
  {{ Form::open(array('route' => 'admin.merchants.store', 'class' => 'form-horizontal')) }}
@endif


  <div class="form-group">
      {{ Form::label('name', 'Entity Name:', array('class'=>'col-md-2 control-label')) }}
      <div class="col-sm-10">
        {{ Form::text('name', Input::old('name'), array('class'=>'form-control', 'placeholder'=>'Name')) }}
      </div>
  </div>

  <div class="form-group">
    {{ Form::label('email', 'Email Address:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::text('email', Input::old('email'), array('class'=>'form-control', 'placeholder'=>'Email Address')) }}
    </div>
  </div>
  <div class="form-group">
    {{ Form::label('phone', 'Phone:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::text('phone', Input::old('phone'), array('class'=>'form-control', 'placeholder'=>'Phone')) }}
    </div>
  </div>

  <div class="form-group">
      {{ Form::label('users', 'Assigned Users(select):', array('class'=>'col-md-2 control-label')) }}
      <div class="col-sm-10">
        {{ Form::text('users-search', '', array('class'=>'form-control', 'id'=>'user-search', 'placeholder'=>'Type to search for users to allocate')) }}
        <p></p>
        <ul class="list-group" id="users-holder">
          @if(isset($merchant))
            @foreach($merchant->users as $user)
              @include('merchants.partials.user', ['user'=>$user])
            @endforeach
          @endif
        </ul>
      </div>
  </div>

  <div class="form-group">
      {{ Form::label('businesses', 'Assigned Venues:', array('class'=>'col-md-2 control-label')) }}
      <div class="col-sm-10">
        {{ Form::text('businesses-search', '', array('class'=>'form-control', 'id'=>'business-search', 'placeholder'=>'Type to search for users to allocate')) }}
        <p></p>
        <ul class="list-group" id="businesses-holder">
          @if(isset($merchant))
            @foreach($merchant->businesses as $business)
              @include('merchants.partials.business', ['business'=>$business])
            @endforeach
          @endif
        </ul>
      </div>
  </div>

  <div class="form-group">
      {{ Form::label('sales_admins', 'Sales POC:', array('class'=>'col-md-2 control-label')) }}
      <div class="col-sm-10">
        {{ Form::select('sales_admins[]', User::select()->byPocs()->get()->lists('selectable_full_name', 'id')->all(), isset($merchant)?$merchant->pocId():'', array('class'=>'form-control', 'id'=>'business-search', 'placeholder'=>'Type to search for users to allocate')) }}
      </div>
  </div>
  <div class="form-group">
    {{ Form::label('tan', 'TAN:', array('class'=>'col-md-2 control-label')) }}
    <div class="col-sm-10">
      {{ Form::text('tan', Input::old('tan'), array('class'=>'form-control', 'placeholder'=>'TAN')) }}
    </div>
  </div>


<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Save', array('class' => 'btn btn-lg btn-primary')) }}
      @if(isset($merchant))
        {{ link_to_route('admin.merchants.show', 'Cancel', $merchant->id, array('class' => 'btn btn-lg btn-default')) }}
      @endif
    </div>
</div>

{{ Form::close() }}
<script type="text/javascript">
$(function(){
  $('#user-search').autocomplete({
    source:'/crm/merchants/get-potential-clients',
    select: function(event, ui){
      $('#users-holder').append(ui.item.html);
    },
  }).autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( '<div >' + item.id + ' - ' +item.name + '<small>('+item.email+')</small></div>')
      .appendTo( ul );
  };
  $('#business-search').autocomplete({
    source:'/crm/merchants/get-clients-outlets',
    select: function(event, ui){
      $('#businesses-holder').append(ui.item.html);
    },
  }).autocomplete( "instance" )._renderItem = function( ul, item ) {
    return $( "<li>" )
      .append( '<div >' + item.id + ' - ' +item.name + '<small>('+item.zone_cache+')</small></div>' )
      .appendTo( ul );
  };  

  $(document).on('click', '.deletable-link', function(){
    $(this).prevAll('.deletable').first().attr('checked', true);
    $(this).parents('li').first().css('backgroundColor', 'red').fadeOut( "slow", function() {
      $(this).remove();
    });
  });


});
</script>