routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {
    Route::get('/auth/login', 'SiteController@login');

Route::group(['middleware'=>['restrict.access']], function(){

  Route::group(array('prefix'=>'sms' ), function(){
    Route::get('/', ['as'=>'admin.sms.index', 'uses'=>'SmsController@index']);
    Route::get('send', ['as'=>'admin.sms.get', 'uses'=>'SmsController@getSend']);
    Route::post('send', ['as'=>'admin.sms.post', 'uses'=>'SmsController@postSend']);
  });


Route::group(array('prefix'=>'content'), function(){
  Route::get('/', ['as'=>'content.dashboard', 'uses'=>'SiteController@contentDashboard']);
  Route::resource('businesses', 'BusinessesController', array('names' => mzk_route_helper('businesses', 'admin')));
  Route::resource('groups', 'GroupsController', array('names' => mzk_route_helper('groups', 'admin')));
  Route::resource('categories', 'CategoriesController', array('names' => mzk_route_helper('categories', 'admin')));
  Route::resource('zones', 'ZonesController', array('names' => mzk_route_helper('zones', 'admin')));
  Route::resource('highlights', 'HighlightsController', array('names' => mzk_route_helper('highlights', 'admin')));
  Route::resource('cities', 'CitiesController', array('names' => mzk_route_helper('cities', 'admin')));
  Route::resource('services', 'ServicesController', array('names' => mzk_route_helper('services', 'admin')));

  Route::get('businesses/{id}/photos', ['as'=>'admin.businesses.show.photos', 'uses'=>'BusinessesController@getPhotos']);
  Route::post('businesses/{id}/photos', ['as'=>'admin.businesses.save.photos', 'uses'=>'BusinessesController@postPhotos']);
  Route::post('businesses/{id}/bulk/photos', ['as'=>'admin.businesses.save.bulk.photos', 'uses'=>'BusinessesController@postBulkPhotos']);

  Route::post('businesses/{id}/stock/photos', ['as'=>'admin.businesses.save.stock.photo', 'uses'=>'BusinessesController@postStockPhoto']);

  Route::get('businesses/{id}/rate-cards', ['as'=>'admin.businesses.show.rate_cards', 'uses'=>'BusinessesController@getRateCards']);
  Route::post('businesses/{id}/rate-cards', ['as'=>'admin.businesses.save.rate_cards', 'uses'=>'BusinessesController@postRateCards']);

  Route::get('businesses/{id}/services', ['as'=>'admin.businesses.show.services', 'uses'=>'BusinessesController@getServices']);
  Route::post('businesses/{id}/services', ['as'=>'admin.businesses.save.services', 'uses'=>'BusinessesController@postServices']);

  Route::get('businesses/{id}/copy-services', ['as'=>'admin.businesses.copyable.services', 'uses'=>'BusinessesController@getCopyServices']);
  Route::post('businesses/{id}/copy-services', ['as'=>'admin.businesses.copy.services', 'uses'=>'BusinessesController@postCopyServices']);

  Route::get('businesses/{id}/modules', ['as'=>'admin.businesses.show.modules', 'uses'=>'BusinessesController@getModules']);
  Route::post('businesses/{id}/modules', ['as'=>'admin.businesses.save.modules', 'uses'=>'BusinessesController@postModules']);

  Route::get('businesses/{id}/toogle-featured', ['as'=>'admin.businesses.toggle-featured', 'uses'=>'BusinessesController@toggleFeatured']);
  Route::get('businesses/{id}/resluggify', ['as'=>'admin.businesses.resluggify', 'uses'=>'BusinessesController@resluggify']);
  Route::get('businesses/{id}/offers', ['as'=>'admin.businesses.show.offers', 'uses'=>'BusinessesController@getOffers']);
  Route::post('businesses/{id}/offers', ['as'=>'admin.businesses.save.offers', 'uses'=>'BusinessesController@postOffers']);

  Route::get('businesses/{id}/timings', ['as'=>'admin.businesses.get.timings', 'uses'=>'BusinessesController@getTimings']);
  Route::post('businesses/{id}/timings', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postTimings']);
  Route::get('businesses/{id}/location', ['as'=>'admin.businesses.get.location', 'uses'=>'BusinessesController@getLocation']);
  Route::post('businesses/{id}/location', ['as'=>'admin.businesses.post.location', 'uses'=>'BusinessesController@postLocation']);
  Route::post('businesses/{id}/delete-service', ['as'=>'admin.businesses.services.destroy', 'uses'=>'BusinessesController@deleteOneBusinessService']);

  Route::get('businesses/{id}/generate-old-id', ['as'=>'admin.businesses.generate-old-id', 'uses'=>'BusinessesController@generateOldId']);

});


Route::group(array('prefix'=>'crm'), function(){
  Route::get('/', ['as'=>'crm.dashboard', 'uses'=>'SiteController@crmDashboard']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));


  Route::post('upload-file', ['as'=>'crm.file-upload', 'uses'=>'SiteController@uploadFile']);

  Route::get('businesses/{id}/virtual_numbers/allocate', ['as'=>'admin.virtual_numbers.for.business.allocate',
                                'uses'=>'Virtual_number_allocationsController@getAllocateForBusiness']);
  Route::get('businesses/{id}/virtual_numbers/deallocate', ['as'=>'admin.virtual_numbers.for.business.deallocate',
                                'uses'=>'Virtual_number_allocationsController@deallocate']);
  Route::get('businesses/{id}/virtual_numbers', ['as'=>'admin.businesses.virtual_numbers.show',
                                          'uses'=>'BusinessesController@getVirtualNumberAllocation']);
  Route::get('businesses/{id}/call_logs', ['as'=>'admin.businesses.call_logs',
                                          'uses'=>'Call_logsController@getIndex']);

  Route::get('adverts/get/avalable/slots', ['as'=>'crm.adverts.get.slots', 'uses'=>'AdvertsController@getAvailableSlots']);

  Route::delete('campaigns/adverts/delete/{id}',array('uses' => 'AdvertsController@deleteOne', 'as' => 'admin.adverts.single.destroy'));
  Route::get('campaigns/edit-allocated-slots/{id}', ['as'=>'crm.campaigns.edit.slots', 'uses'=>'CampaignsController@getEditableAverts']);

  Route::resource('adverts', 'AdvertsController', array('names' => mzk_route_helper('adverts', 'admin')));
  Route::resource('campaigns', 'CampaignsController', array('names' => mzk_route_helper('campaigns', 'admin')));
  Route::resource('wikis', 'WikisController', array('names' => mzk_route_helper('wikis', 'admin')));
 
  Route::post('adverts/updatable', ['uses'=>'AdvertsController@updatable', 'as'=>'admin.adverts.updatable']);

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::get('merchants/toggle-leads-access-for-business/{id}', ['as'=>'admin.merchants.toggle_leads_access.businesses', 'uses'=>'MerchantsController@toggleLeadsAccessForBusiness']);
  Route::get('merchants/toggle-resumes-access-for-business/{id}', ['as'=>'admin.merchants.toggle_resumes_access.businesses', 'uses'=>'MerchantsController@toggleResumesAccessForBusiness']);
  Route::get('merchants/toggle-debug-for-business/{id}', ['as'=>'admin.merchants.toggle_debug.businesses', 'uses'=>'BusinessesController@toggleDebug']);


  Route::get('merchants/export', ['as'=>'admin.merchants.export', 'uses'=>'MerchantsController@export']);
  Route::get('merchants/global', ['as'=>'admin.merchants.global', 'uses'=>'MerchantsController@globalIndex']);
  Route::get('merchants/export/global', ['as'=>'admin.merchants.export.global', 'uses'=>'MerchantsController@exportGlobalIndex']);

  Route::get('merchants/access/{merchant_id}/{user_id}', ['as'=>'admin.merchants.access.form', 'uses'=>'MerchantsController@getFormForModuleAccess']);
  Route::post('merchants/access/post', ['as'=>'admin.merchants.access', 'uses'=>'MerchantsController@postModuleAccess']);

  Route::get('merchants/get-potential-clients', ['as'=>'admin.merchants.potential.clients', 'uses'=>'MerchantsController@getUsersForMerchant']);
  Route::get('merchants/get-clients-outlets', ['as'=>'admin.merchants.client.outlets', 'uses'=>'MerchantsController@getOutletsForMerchant']);
  Route::resource('merchants', 'MerchantsController', array('names' => mzk_route_helper('merchants', 'admin')));

  Route::get('merchants/call-logs/get-businesses', ['as'=>'admin.merchants.call_logs.businesses', 'uses'=>'MerchantsController@getOutletsForMerchantInvoiceForm']);

  Route::resource('virtual_number_allocations', 'Virtual_number_allocationsController', array('names' => mzk_route_helper('virtual_number_allocations', 'admin')));

  Route::resource('virtual_numbers', 'Virtual_numbersController', array('names' => mzk_route_helper('virtual_numbers', 'admin')));

});

  Route::get('session', function() {
      return Session::all();
  });

  Route::get('/welcome', function () {
    return view('welcome');
  });
  Route::get('/', 'SiteController@index');

  Route::get('/change/locale/{id}', ['uses'=>'SiteController@changeLocale', 'as'=>'change.locale']);
  Route::get('/auth/logout', ['as'=>'users.logout', 'uses'=>'SiteController@logout']);
});
  
});

app/Http/Controllers/Virtual_number_allocationsController.php
<?php
namespace App\Http\Controllers;

use Validator;
//use Vinelab\Http\Client as HttpClient;

use GuzzleHttp\Client as HttpClient;

use Illuminate\Support\Facades\Input;


use App\Http\Controllers\Controller;

class Virtual_number_allocationsController extends Controller {

  /**
   * Virtual_number_allocation Repository
   *
   * @var Virtual_number_allocation
   */
  protected $virtual_number_allocation, $business, $virtual_number;

  public function __construct(\App\Models\Business $business, 
                              \App\Models\Virtual_number $virtual_number, 
                              \App\Models\Virtual_number_allocation $virtual_number_allocation)
  {
    $this->business = $business;
    $this->virtual_number = $virtual_number;

    $this->virtual_number_allocation = $virtual_number_allocation;
  }

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $virtual_number_allocations = $this->virtual_number_allocation->all();
    $businesses = $this->business->query()->byLocale();
    $params = [];
    $input = Input::all();

    if(Input::has('search') && ($input['search']!="")){
      $businesses->search($input['search']);
      $params['name'] = $input['search'];
      $params['search'] = $input['search'];
    }

    if(Input::has('sort') && ($input['sort']!='')){
      $params['sort'] = $input['sort'];
      switch($params['sort']){
        case 'idAsc':
          $businesses->orderBy('id', 'ASC');
        break; 
        case 'idDesc':
          $businesses->orderBy('id', 'DESC');
        break; 
        case 'nameAsc':
          $businesses->orderBy('name', 'ASC');
        break; 
        case 'nameDesc':
          $businesses->orderBy('name', 'DESC');
        break; 
        case 'lastUpdateAsc':
          $businesses->orderBy('updated_at', 'ASC');
        break; 
        case 'lastUpdateDesc':
          $businesses->orderBy('updated_at', 'DESC');
        break; 
      }
    }else{
      $businesses->orderBy('businesses.id', 'DESC');
    }


    $businesses = $businesses->paginate(20);

    //$this->layout = view('layouts.admin');
    return   view('virtual_number_allocations.index', compact('params', 'businesses', 'virtual_number_allocations'));
  }



  public function getAllocateForBusiness($id){
    $business = $this->business->findOrFail($id);
    $virtual_numbers = $this->virtual_number->onlyAllocatable();
    //$this->layout = view('layouts.admin');
    return   view('virtual_number_allocations.allocate', compact('virtual_numbers', 'business'));

  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */

  public function create(){
    //$this->layout = view('layouts.admin');
    return   view('virtual_number_allocations.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */

  public function store()
  {
    $input = Input::except('_token', 'valid_until');
    $validation = Validator::make($input, \App\Models\Virtual_number_allocation::$rules);
//SELECT `api_virtualnumberallocation`.`id`,
//    `api_virtualnumberallocation`.`description`,
//    `api_virtualnumberallocation`.`created_at`,
//    `api_virtualnumberallocation`.`updated_at`,
//    `api_virtualnumberallocation`.`desc`,
//    `api_virtualnumberallocation`.`starts`,
//    `api_virtualnumberallocation`.`ends`,
//    `api_virtualnumberallocation`.`state`,
//    `api_virtualnumberallocation`.`phone_1`,
//    `api_virtualnumberallocation`.`phone_2`,
//    `api_virtualnumberallocation`.`phone_3`,
//    `api_virtualnumberallocation`.`is_ppl`,
//    `api_virtualnumberallocation`.`is_ivr_enabled`,
//    `api_virtualnumberallocation`.`business_id`,
//    `api_virtualnumberallocation`.`virtual_number_id`,
//    `api_virtualnumberallocation`.`old_id`
//FROM `fabogo_local`.`api_virtualnumberallocation`;

    if ($validation->passes()){
      $input['starts'] = \Carbon\Carbon::now();
      $virtual_number = \App\Models\Virtual_number::find($input['virtual_number_id']);
      //dump($input);die();
      $allocation = new \App\Models\Virtual_number_allocation();//$this->virtual_number_allocation->new();
      foreach($input as $ii=>$vv){
        $allocation->$ii = $vv;
      }

      $allocation->desc = 'Virtual number ID '.$input['virtual_number_id'].' allocated to '.$input['phone_1'];

      $allocation->save();


      //create($input);
      $client = new HttpClient();
      $url = 'http://etsintl.kapps.in/webapi/mazkara/api/mazkara_agent_mapping.py?auth_key=51c41934-94b1-4be7-82c2-6531251a76ab';
      $url .='&knowlarity_number='.$virtual_number->body.'&mapped_number='.
                                join(',', array_filter([ trim($input['phone_1']),
                                                          trim($input['phone_2']),
                                                          trim($input['phone_3'])])); 

      $response = $client->get($url);
      //$response = mzk_xml2array($response->xml());

      $business = $this->business->findOrFail($input['business_id']);

      return redirect()->route('admin.merchants.show', $business->merchant_id)
                          ->with('message', 'Success');//$response);

      return redirect()->route('admin.businesses.virtual_numbers.show', $input['business_id'])
                          ->with('message', 'Success');//$response);
    }

    return redirect()->back()
      ->withInput()
      ->withErrors($validation)
      ->with('message', 'There were validation errors.');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    $virtual_number_allocation = $this->virtual_number_allocation->findOrFail($id);

    //$this->layout = view('layouts.admin');
    return   view('administration.virtual_number_allocations.show', compact('virtual_number_allocation'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $virtual_number_allocation = $this->virtual_number_allocation->find($id);

    if (is_null($virtual_number_allocation))
    {
      return redirect()->route('virtual_number_allocations.index');
    }

    //$this->layout = view('layouts.admin');
    return   view('administration.virtual_number_allocations.edit', compact('virtual_number_allocation'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function deallocate($id)
  {
    $input = array_except(Input::all(), '_method');
    $virtual_number_allocation = $this->virtual_number_allocation->find($id);
    $virtual_number_allocation->deallocate();

    $virtual_number = \App\Models\Virtual_number::find($virtual_number_allocation->virtual_number_id);

    $client = new HttpClient();
    $url = 'http://etsintl.kapps.in/webapi/mazkara/api/mazkara_agent_mapping.py?auth_key=51c41934-94b1-4be7-82c2-6531251a76ab';
    $url .='&knowlarity_number='.$virtual_number->body.
                      '&mapped_number=None'; 

    $response = $client->get($url);
    
    //$response = mzk_xml2array($response->xml());

    return redirect()->back()->with('message', 'Ok');
  }




  public function updateVirtualNumberAllocation(){
    $input = Input::all();

    $data = ['id' => $input['pk']];

    $virtual_number_allocation = \App\Models\Virtual_number_allocation::find($data['id']);

    $virtual_number_allocation->$input['name'] = $input['value'];
    $virtual_number_allocation->save();
    return redirect()->back();

  }



  public function update($id)
  {
    $input = array_except(Input::all(), '_method');
    $validation = Validator::make($input, \App\Models\Virtual_number_allocation::$rules);

    if ($validation->passes())
    {
      $virtual_number_allocation = $this->virtual_number_allocation->find($id);
      $virtual_number_allocation->update($input);

      return redirect()->route('admin.virtual_number_allocations.show', $id);
    }

    return redirect()->route('admin.virtual_number_allocations.edit', $id)
      ->withInput()
      ->withErrors($validation)
      ->with('message', 'There were validation errors.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    $this->virtual_number_allocation->find($id)->delete();

    return redirect()->route('admin.virtual_number_allocations.index');
  }

}

resources/views/virtual_number_allocations/allocate.blade.php
@extends('layouts.panel-crm')
@section('content')
<section class="content-header">
  <h1>
    Allocate a virtual number to {!! $business->name !!}
  </h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="/crm">CRM</a></li>
    <li class="active">Virtual Number</li>
  </ol>
</section>
<section class="content">
  <div class="box box-primary">
    <div class="box-body">

<div class="row">
  <div class="col-md-10 col-md-offset-2">

    @if ($errors->any())
    	<div class="alert alert-danger">
  	    <ul>
          {!! implode('', $errors->all('<li class="error">:message</li>')) !!}
        </ul>
    	</div>
    @endif
  </div>
</div>


{!! BootForm::openHorizontal(['sm' => [4, 8], 'lg' => [3, 8] ])->post()->action(route('admin.virtual_number_allocations.store'))
                                ->encodingType('multipart/form-data') !!}

  @if (Session::get('error'))
    <div class="alert alert-error alert-danger">
      {!! is_array(Session::get('error'))?join(',', Session::get('error')):Session::get('error') !!}
    </div>
  @endif
  @if (Session::get('notice'))
    <div class="alert alert-success">
      {!! is_array(Session::get('notice'))?join(',', Session::get('notice')):Session::get('notice') !!}
    </div>
  @endif

  {!! BootForm::select('Virtual number', 'virtual_number_id', $virtual_numbers->byLocale()->onlyActive()->pluck('body','id')->all()) !!}
  {!! BootForm::text('Primary Phone number',   'phone_1')->placeholder('Primary phone number to redirect to') !!}
  {!! BootForm::text('Secondary Phone number', 'phone_2')->placeholder('Secondary phone number to redirect to') !!}
  {!! BootForm::text('Tertiary Phone number',  'phone_3')->placeholder('Tertiary phone number to redirect to') !!}
  {!! BootForm::hidden('business_id', $business->id)->value($business->id) !!}
  {!! BootForm::textarea('Notes', 'desc')->placeholder('Notes') !!}
  {!! BootForm::text('Valid Until',  'valid_until')->placeholder('Date Valid till')->addClass('dateinput') !!}
  {!! BootForm::select('Is IVR enabled', 'is_ivr_enabled', ['0'=>'No', '1'=>'Yes']) !!}


  {!! BootForm::radio('Yes! Activate PPL', 'is_ppl', 1) !!}
  {!! BootForm::radio('NO PPL', 'is_ppl', 0) !!}

  {!! BootForm::hidden('state', 'active')->value('active') !!}
  {!! BootForm::token() !!}
  {!! BootForm::submit('Allocate Number') !!}

{!! BootForm::close() !!}
</div>
</div>
</section>
<script type="text/javascript">
$(function(){
  $('.dateinput input').datepicker({ format: "yyyy-mm-dd", autoclose:true });
  $('input.dateinput').datepicker({ format: "yyyy-mm-dd", autoclose:true });
})
</script>
@stop

resources/views/virtual_number_allocations/create.blade.php
@extends('layouts.admin-crm')
@section('content')

<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <h1>Create Virtual_number_allocation</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
</div>

{{ Form::open(array('route' => 'admin.virtual_number_allocations.store', 'class' => 'form-horizontal')) }}

        <div class="form-group">
            {{ Form::label('desc', 'Desc:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('desc', Input::old('desc'), array('class'=>'form-control', 'placeholder'=>'Desc')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('business_id', 'Business_id:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::input('number', 'business_id', Input::old('business_id'), array('class'=>'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('virtual_number_id', 'Virtual_number_id:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::input('number', 'virtual_number_id', Input::old('virtual_number_id'), array('class'=>'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('start', 'Start:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('start', Input::old('start'), array('class'=>'form-control', 'placeholder'=>'Start')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('end', 'End:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('end', Input::old('end'), array('class'=>'form-control', 'placeholder'=>'End')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('state', 'State:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('state', Input::old('state'), array('class'=>'form-control', 'placeholder'=>'State')) }}
            </div>
        </div>


<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Create', array('class' => 'btn btn-lg btn-primary')) }}
    </div>
</div>

{{ Form::close() }}

@stop

resources/views/virtual_number_allocations/index.blade.php
@extends('layouts.admin-crm')
@section('content')

<h1>All Virtual_number_allocations</h1>

<p>{{ link_to_route('admin.virtual_number_allocations.create', 'Add New Virtual_number_allocation', null, array('class' => 'btn btn-lg btn-success')) }}</p>



<div class="well">
  {{ Form::open(array('style' => 'display: inline-block;', 'class'=>'form-inline', 'method' => 'GET')) }}
    {{ Form::text(  'byID', Input::get('byID'), array('class'=>'form-control col-md-2', 'style'=>'width:150px;',
                    'placeholder'=>'By Business ID')) }}

    {{ Form::text('search', Input::get('search'), array('class'=>'form-control col-md-2', 'style'=>'width:150px;', 'placeholder'=>'Search')) }}
    {{ Form::text(  'bySlipID', Input::get('bySlipID'), array('class'=>'form-control col-md-3', 'style'=>'width:200px;',
                    'placeholder'=>'By Slip ID')) }}
    {{ Form::text(  'byLotID', Input::get('byLotID'), array('class'=>'form-control col-md-3', 'style'=>'width:200px;',
                    'placeholder'=>'By Lot ID')) }}
    
    {{ Form::select('sort', ([ ''=>'Sort by?', 
                              'idAsc'=>'ID Ascending', 
                              'idDesc'=>'ID Descending', 
                              'nameAsc'=>'Name Ascending', 
                              'nameDesc'=>'Name Descending', 
                              'lastUpdateAsc'=>'Last Update Ascending',
                              'lastUpdateDesc'=>'Last Update Descending',
                              ]),
                           Input::get('sort'), array('class'=>'form-control', 'style'=>'width:150px;', 'placeholder'=>'Service')) }}
    <button type="submit" class="btn btn-default">Filter</button>
  {{ Form::close() }}
</div>


@if ($businesses->count())
  <div class="list-group">
		@foreach ($businesses as $business)
      <a href="{{ route('admin.businesses.virtual_numbers.show', array($business->id) ) }}" class="list-group-item">
        <div class="pull-right">
          <small>Last Updated {{{ Date::parse($business->updated_at)->ago() }}}</small>
        </div>
        <h4 class="list-group-item-heading">
          {{{ $business->id }}} -          
          {{{ $business->name }}}
        </h4>
        <p class="list-group-item-text">
          <b>Phone:</b>{{{ join( ',', $business->phone) }}}
          <b>Email:</b>{{{ join( ',',$business->email) }}}
          <br/>
          <b>Website:</b>{{{ $business->website }}}
          <b>Zone:</b>{{{ $business->zone_cache }}}
        </p>
      </a>
		@endforeach      
  </div>

  <div class="row">
    <div class="col-md-12">
	{{ $businesses->appends($params)->render() }}
  <div class="pull-right">
    {{ count($businesses) }} / {{ $businesses->total() }} entries
  </div></div>
</div>
@else
	There are no businesses
@endif

@stop

resources/views/virtual_number_allocations/show.blade.php
@extends('layouts.admin-crm')
@section('content')

<h1>Show Virtual_number_allocation</h1>

<p>{{ link_to_route('admin.virtual_number_allocations.index', 'Return to All virtual_number_allocations', null, array('class'=>'btn btn-lg btn-primary')) }}</p>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Desc</th>
				<th>Business_id</th>
				<th>Virtual_number_id</th>
				<th>Start</th>
				<th>End</th>
				<th>State</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>{{{ $virtual_number_allocation->desc }}}</td>
			<td>{{{ $virtual_number_allocation->business_id }}}</td>
			<td>{{{ $virtual_number_allocation->virtual_number_id }}}</td>
			<td>{{{ $virtual_number_allocation->start }}}</td>
			<td>{{{ $virtual_number_allocation->end }}}</td>
			<td>{{{ $virtual_number_allocation->state }}}</td>
      <td>
          {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('admin.virtual_number_allocations.destroy', $virtual_number_allocation->id))) }}
              {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
          {{ Form::close() }}
          {{ link_to_route('admin.virtual_number_allocations.edit', 'Edit', array($virtual_number_allocation->id), array('class' => 'btn btn-info')) }}
      </td>
		</tr>
	</tbody>
</table>

@stop